import { Platform } from '../core/types';

export const PLATFORMS: Record<string, Platform> = {
  INSTAGRAM: {
    id: "INSTAGRAM",
    label: "Instagram",
    icon: "📸",
    color: "#E1306C",
    maxChars: 2200,
    supportsMedia: ["image", "video", "carousel", "reel", "story"],
    requiresMedia: false,
    apiEndpoint: "https://graph.instagram.com/v18.0/media",
    authRequired: "instagram_basic,instagram_content_publish",
  },
  FACEBOOK: {
    id: "FACEBOOK",
    label: "Facebook",
    icon: "👥",
    color: "#1877F2",
    maxChars: 63206,
    supportsMedia: ["image", "video", "carousel"],
    requiresMedia: false,
    apiEndpoint: "https://graph.facebook.com/v18.0/{page-id}/posts",
    authRequired: "pages_manage_posts,pages_read_engagement",
  },
  TIKTOK: {
    id: "TIKTOK",
    label: "TikTok",
    icon: "🎵",
    color: "#010101",
    maxChars: 2200,
    supportsMedia: ["video"],
    requiresMedia: true,
    apiEndpoint: "https://open.tiktokapis.com/v2/post/publish/video/init/",
    authRequired: "video.publish,video.upload",
  },
  LINKEDIN: {
    id: "LINKEDIN",
    label: "LinkedIn",
    icon: "💼",
    color: "#0A66C2",
    maxChars: 3000,
    supportsMedia: ["image", "video"],
    requiresMedia: false,
    apiEndpoint: "https://api.linkedin.com/v2/ugcPosts",
    authRequired: "w_member_social",
  },
  YOUTUBE: {
    id: "YOUTUBE",
    label: "YouTube",
    icon: "▶️",
    color: "#FF0000",
    maxChars: 5000,
    supportsMedia: ["video"],
    requiresMedia: true,
    apiEndpoint: "https://www.googleapis.com/upload/youtube/v3/videos",
    authRequired: "https://www.googleapis.com/auth/youtube.upload",
  },
  THREADS: {
    id: "THREADS",
    label: "Threads",
    icon: "🧵",
    color: "#000000",
    maxChars: 500,
    supportsMedia: ["image", "video"],
    requiresMedia: false,
    apiEndpoint: "https://graph.threads.net/v1.0/{user-id}/threads",
    authRequired: "threads_basic,threads_content_publish",
  },
};

export const PLATFORM_LIST = Object.values(PLATFORMS);
